# Generated by Django 5.2.5 on 2025-09-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoZK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.BigIntegerField(unique=True)),
                ('terminal_sn', models.CharField(db_index=True, max_length=64)),
                ('codigo', models.CharField(db_index=True, max_length=32)),
                ('event_time', models.DateTimeField(db_index=True)),
                ('area_alias', models.CharField(blank=True, max_length=128)),
                ('upload_time', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
