# Generated by Django 5.2.5 on 2025-09-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=32)),
                ('fecha', models.DateField(db_index=True)),
                ('tipo', models.CharField(choices=[('DESAYUNO', 'Desayuno'), ('ALMUERZO', 'Almuerzo')], db_index=True, max_length=16)),
                ('primer_evento', models.DateTimeField()),
                ('terminal_sn', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['fecha', 'tipo'], name='registros_c_fecha_1ff8e2_idx')],
                'unique_together': {('codigo', 'fecha', 'tipo')},
            },
        ),
    ]
